apiVersion: apps/v1
kind: Deployment
metadata:
  name: dovecot
  labels:
    app: dovecot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dovecot
  template:
    metadata:
      labels:
        app: dovecot
    spec:
      containers:
        - name: dovecot
          image: {{ .Values.dovecot.image }}
          ports:
            - containerPort: 143  # IMAP
            - containerPort: 993  # IMAPS
          volumeMounts:
            - name: dovecot-config
              mountPath: /etc/dovecot/dovecot.conf
              subPath: dovecot.conf
            - name: dovecot-mail
              mountPath: /var/mail
      volumes:
        - name: dovecot-config
          configMap:
            name: dovecot-config
        - name: dovecot-mail
          persistentVolumeClaim:
            claimName: dovecot-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dovecot.storageSize }}

---

apiVersion: v1
kind: Service
metadata:
  name: dovecot
  labels:
    app: dovecot
spec:
  type: ClusterIP
  selector:
    app: dovecot
  ports:
    - port: 143
      targetPort: 143
    - port: 993
      targetPort: 993
