apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dovecot.name }}
  labels:
    app: {{ .Values.dovecot.name }}
spec:
  replicas: {{ .Values.dovecot.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.dovecot.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.dovecot.name }}
    spec:
      containers:
        - name: {{ .Values.dovecot.name }}
          image: {{ .Values.dovecot.image }}
          ports:
            - containerPort: 993  # IMAPS
            - containerPort: 110  # POP3
            - containerPort: 143  # IMAP
            - containerPort: 25   # SMTP
          volumeMounts:
            - name: dovecot-data
              mountPath: /var/lib/dovecot
      volumes:
        - name: dovecot-data
          persistentVolumeClaim:
            claimName: dovecot-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dovecot-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dovecot.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dovecot.name }}
  labels:
    app: {{ .Values.dovecot.name }}
spec:
  ports:
    - port: 993
      targetPort: 993
      protocol: TCP
      name: imaps
    - port: 110
      targetPort: 110
      protocol: TCP
      name: pop3
    - port: 143
      targetPort: 143
      protocol: TCP
      name: imap
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp
  selector:
    app: {{ .Values.dovecot.name }}
