apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets.name}}
      containers:
        - name: keycloak
          image: {{ .Values.keycloak.image }}
          command:
            - "/opt/keycloak/bin/kc.sh"
            - "start-dev"
            - "--import-realm"
          ports:
            - containerPort: {{.Values.application.env.KC_HTTP_PORT}}
          env:
            - name: KC_HTTP_PORT
              value: "{{.Values.application.env.KC_HTTP_PORT}}"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              value: {{ .Values.application.env.KEYCLOAK_ADMIN_USERNAME | quote }}
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rechnomat-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KEYCLOAK_REALM
              value: {{ .Values.application.env.KEYCLOAK_REALM | quote }}
            - name: KEYCLOAK_CLIENT_ID
              value: {{ .Values.application.env.KEYCLOAK_CLIENT_ID | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - port: {{.Values.application.env.KC_HTTP_PORT}}
      targetPort: {{.Values.application.env.KC_HTTP_PORT}}
      protocol: TCP
      name: http
  selector:
    app: keycloak
