apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mailpit.name }}
  labels:
    app: {{ .Values.mailpit.name }}
spec:
  replicas: {{ .Values.mailpit.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mailpit.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mailpit.name }}
    spec:
      containers:
        - name: {{ .Values.mailpit.name }}
          image: {{ .Values.mailpit.image }}
          ports:
            - containerPort: 1025  # SMTP
            - containerPort: 8025  # Web UI
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mailpit.name }}
  labels:
    app: {{ .Values.mailpit.name }}
spec:
  ports:
    - port: 1025
      targetPort: 1025
      protocol: TCP
      name: smtp
    - port: 8025
      targetPort: 8025
      protocol: TCP
      name: web
  selector:
    app: {{ .Values.mailpit.name }}
