apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
        - name: mailpit
          image: {{ .Values.mailpit.image }}
          ports:
            - containerPort: 1025  # SMTP
            - containerPort: 8025  # Web UI

---

apiVersion: v1
kind: Service
metadata:
  name: mailpit
  labels:
    app: mailpit
spec:
  type: ClusterIP
  selector:
    app: mailpit
  ports:
    - port: 1025
      targetPort: 1025
    - port: 8025
      targetPort: 8025
