apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.application.env.DB_DEV_USER | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rechnomat-secrets
                  key: DB_DEV_PASS
            - name: POSTGRES_DB
              value: {{ .Values.application.env.DB_DEV_NAME | quote }}

          volumeMounts:
            - name: postgres-dev-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-dev-data
          persistentVolumeClaim:
            claimName: postgres-dev-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres-dev