apiVersion: v1
kind: Secret
metadata:
  name: postgres-dev-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.devPassword | b64enc }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-dev
  template:
    metadata:
      labels:
        app: postgres-dev
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-dev-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: dev_db
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-dev-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-dev-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-dev
  labels:
    app: postgres-dev
spec:
  type: ClusterIP
  selector:
    app: postgres-dev
  ports:
    - port: 5432
      targetPort: 5432