apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-it
  labels:
    app: postgres-it
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-it
  template:
    metadata:
      labels:
        app: postgres-it
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: {{ .Values.application.env.DB_IT_USER | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rechnomat-secrets
                  key: DB_IT_PASS
            - name: POSTGRES_DB
              value: {{ .Values.application.env.DB_IT_NAME | quote }}

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-it-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-it-pvc
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storageSize }}

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-it
  labels:
    app: postgres-it
spec:
  type: ClusterIP
  selector:
    app: postgres-it
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
