apiVersion: v1
kind: Secret
metadata:
  name: application-secrets
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.database.devPassword | b64enc }}
  DATABASE_IT_PASSWORD: {{ .Values.database.itPassword | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.adminPassword | b64enc }}
  WEBDAV_USERNAME: {{ .Values.webdav.username | b64enc }}
  WEBDAV_PASSWORD: {{ .Values.webdav.password | b64enc }}
