apiVersion: v1
kind: Secret
metadata:
  name: rechnomat-secrets
type: Opaque
data:
  DB_DEV_PASS: {{.Values.application.secrets.DB_DEV_PASS | b64enc | quote}}
  DB_IT_PASS: {{.Values.application.secrets.DB_IT_PASS | b64enc | quote}}
  KEYCLOAK_ADMIN_PASSWORD: {{.Values.application.secrets.KEYCLOAK_ADMIN_PASSWORD | b64enc | quote}}
  WEBDAV_PASS: {{.Values.application.secrets.WEBDAV_PASS | b64enc | quote}}

