apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  labels:
    app: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
        - name: webdav
          image: {{ .Values.webdav.image }}
          ports:
            - containerPort: 80
          env:
            - name: WEBDAV_HOST
              value: {{ .Values.application.env.WEBDAV_HOST | quote }}
            - name: WEBDAV_PORT
              value: {{ .Values.application.env.WEBDAV_PORT | quote }}
            - name: WEBDAV_USER
              value: {{ .Values.application.env.WEBDAV_USER | quote }}
            - name: WEBDAV_PASS
              valueFrom:
                secretKeyRef:
                  name: rechnomat-secrets
                  key: WEBDAV_PASS
          volumeMounts:
            - name: webdav-data
              mountPath: /var/lib/webdav
      volumes:
        - name: webdav-data
          persistentVolumeClaim:
            claimName: webdav-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.webdav.storageSize }}

---

apiVersion: v1
kind: Service
metadata:
  name: webdav
  labels:
    app: webdav
spec:
  type: ClusterIP
  selector:
    app: webdav
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http