apiVersion: v1
kind: Secret
metadata:
  name: webdav-secrets
type: Opaque
data:
  WEBDAV_USERNAME: {{ .Values.webdav.username | b64enc }}
  WEBDAV_PASSWORD: {{ .Values.webdav.password | b64enc }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  labels:
    app: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
        - name: webdav
          image: {{ .Values.webdav.image }}
          ports:
            - containerPort: 80
          env:
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: webdav-secrets
                  key: WEBDAV_USERNAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webdav-secrets
                  key: WEBDAV_PASSWORD
          volumeMounts:
            - name: webdav-storage
              mountPath: /var/lib/dav
      volumes:
        - name: webdav-storage
          persistentVolumeClaim:
            claimName: webdav-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webdav-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.webdav.storageSize }}

---

apiVersion: v1
kind: Service
metadata:
  name: webdav
  labels:
    app: webdav
spec:
  type: ClusterIP
  selector:
    app: webdav
  ports:
    - port: 80
      targetPort: 80
