replicaCount: 1

image:
  repository: docker.io/nikivash/rechnomat
  tag: latest
  pullSecrets:
    name: regcred
  pullPolicy: Always

application:
  name: rechnomat
  port: 9001
  env:
    DB_DEV_URL: "jdbc:postgresql://postgres-dev"
    DB_DEV_PORT: "5432"
    DB_DEV_NAME: "rechnomat"
    DB_DEV_USER: "postgres"

    DB_IT_URL: "jdbc:postgresql://postgres-it"
    DB_IT_PORT: "5432"
    DB_IT_NAME: "it-db"
    DB_IT_USER: "postgres"

    KEYCLOAK_URL: "http://localhost:9990"
    KEYCLOAK_ADMIN_USERNAME: "admin"
    KEYCLOAK_REALM: "SpringBootKeycloak"
    KEYCLOAK_CLIENT_ID: "admin-cli"

    WEBDAV_HOST: "webdav"
    WEBDAV_PORT: "80"
    WEBDAV_USER: "webdav_user"

    #        MAIL_SENDER: "buchhaltung@denktmit.de"
    #        MAIL_SMTP_HOST: "mailpit"
    #        MAIL_SMTP_PORT: "1025"
    #        MAIL_IMAP_HOST: "dovecot"
    #        MAIL_IMAP_PORT: "993"
    #        MAIL_USERNAME: "hallo@denktmit.de"
    #        MAIL_PASSWORD: "pass"

  secrets:
    DB_DEV_PASS: "dev_db_password"
    DB_IT_PASS: "it_db_password"
    KEYCLOAK_ADMIN_PASSWORD: "admin"
    WEBDAV_PASS: "webdav_pass"

service:
  type: ClusterIP
  port: 9001

postgresql:
  image: postgres:16.0
  storageSize: 1Gi

dovecot:
  name: dovecot
  replicaCount: 1
  image: dovecot/dovecot:latest  # Замените на ваш Docker-образ Dovecot
  storageSize: 1Gi

webdav:
  image: bytemark/webdav
  storageSize: 1Gi

mailpit:
  name: mailpit
  replicaCount: 1
  image: axllent/mailpit

keycloak:
  image: quay.io/keycloak/keycloak:latest



