apiVersion: v2
name: argo-cd
type: application
version: 7.6.5
appVersion: v2.12.4
dependencies:
  - name: argo-cd
    version: 7.6.5
    repository: https://argoproj.github.io/argo-helm
    import-values:
      - child: global
        parent: global
