global:
  addPrometheusAnnotations: true

argo-cd:
  controller:
    metrics:
      enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 1
        memory: 1Gi

  crds:
    install: true

  namespace: argocd

  server:
    metrics:
      enabled: true

    # Отключаем Ingress, если не используем его
    ingress:
      enabled: false

    # Меняем тип сервиса на NodePort для прямого доступа
    service:
      type: NodePort
      nodePort: 30080  # Указываем порт, по которому будем обращаться

    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  configs:
    params:
      server.insecure: "true"
    cm:
      url: http://localhost:30080  # Обновляем URL на локальный адрес и порт

  repoServer:
    metrics:
      enabled: true
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 300m
        memory: 1Gi

  applicationSet:
    replicas: 1
    metrics:
      enabled: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  redis:
    metrics:
      enabled: true

    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  notifications:
    metrics:
      enabled: true

    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  dex:
    enabled: false

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
